version: "3.9"
services:
  api:
    container_name: punchcloq-api
    #command: tail -F "haha"
    image: punchcloq-api
    env_file: .env
    ports:
    - 3000:3000
  db:
    container_name: punchcloq-db
    image: postgres:16.2-alpine3.19
    env_file: .env
    ports:
    - 5432:5432

